# Generated by Django 3.0.3 on 2020-02-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='max_temp',
            new_name='max_temperature',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='min_temp',
            new_name='min_temperature',
        ),
    ]
